version: 2
jobs: 
  one:
    docker:
      - image: cimg/python:3.8      
    steps: 
      - checkout 
      - run:
          command: |
            python3 test.py
  two:
    docker:
      - image: cimg/python:3.8      
    steps: 
      - checkout 
      - run:
          command: |
            python3 test.py
  three:
    docker:
      - image: cimg/python:3.8      
    steps: 
      - checkout 
      - run:
          command: |
            python3 test.py
 
workflows:
  version: 2
  build:
    jobs:
      - one
      - two
      - three
